export const DEFAULTS = {
  version: '0.1.0',
  rulesVersion: '0.1.0',
  backupEnabled: true,
  allRules: [
    // Global
    'global/orchestrator',
    // Agents
    'agents/planner',
    'agents/executor',
    'agents/reviewer',
    'agents/debugger',
    'agents/architect',
    'agents/test-engineer',
    'agents/security-reviewer',
    'agents/explore',
    'agents/analyst',
    'agents/verifier',
    'agents/designer',
    'agents/writer',
    'agents/git-master',
    'agents/code-simplifier',
    'agents/critic',
    'agents/scientist',
    'agents/qa-tester',
    'agents/document-specialist',
    'agents/build-fixer',
    'agents/deep-executor',
    'agents/harsh-critic',
    'agents/quality-reviewer',
    // Workflows
    'workflows/autopilot',
    'workflows/tdd',
    'workflows/plan-execute',
    'workflows/ralplan',
    'workflows/ultraqa',
    'workflows/deep-interview',
    'workflows/slop-cleaner',
    'workflows/ralph',
    'workflows/learner',
    'workflows/release',
    // Practices
    'practices/coding-style',
    'practices/testing',
    'practices/security',
    'practices/git-workflow',
    'practices/performance',
    'practices/karpathy-guidelines',
  ],
  presets: {
    minimal: [
      'global/orchestrator',
      'agents/executor',
      'practices/coding-style',
      'practices/security',
    ],
    standard: [
      'global/orchestrator',
      'agents/planner',
      'agents/executor',
      'agents/reviewer',
      'agents/debugger',
      'agents/verifier',
      'agents/build-fixer',
      'workflows/autopilot',
      'workflows/ralph',
      'practices/coding-style',
      'practices/testing',
      'practices/security',
    ],
    full: null, // all rules
  },
} as const
